services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DsWebCrawlerBundle\EventListener\DocumentMetaDataListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }