imports:
    - { resource: services/*.yaml }

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DsWebCrawlerBundle\Configuration\ConfigurationInterface: '@DsWebCrawlerBundle\Configuration\Configuration'
    DsWebCrawlerBundle\Configuration\Configuration: ~

    DsWebCrawlerBundle\Service\CrawlerStateServiceInterface: '@DsWebCrawlerBundle\Service\CrawlerStateService'
    DsWebCrawlerBundle\Service\CrawlerStateService: ~

    DsWebCrawlerBundle\Service\FileWatcherServiceInterface: '@DsWebCrawlerBundle\Service\FileWatcherService'
    DsWebCrawlerBundle\Service\FileWatcherService: ~

    DsWebCrawlerBundle\Service\CrawlerServiceInterface: '@DsWebCrawlerBundle\Service\CrawlerService'
    DsWebCrawlerBundle\Service\CrawlerService: ~

    DsWebCrawlerBundle\Registry\EventSubscriberRegistryInterface: '@DsWebCrawlerBundle\Registry\EventSubscriberRegistry'
    DsWebCrawlerBundle\Registry\EventSubscriberRegistry: ~

    DsWebCrawlerBundle\Twig\Extension\CrawlerExtension:
        tags:
            - { name: twig.extension }
